### ISSUE TITLE
/shop/offre/{id} -> Ajouter status si connecté en tant qu'inf

### ISSUE THREAD

**Issue by chheue** [Mystogunn/neoconnect#184]
Dans Shop/offre/id si tu récupère en tant qu'influenceur, il faudrait renvoyer le statut (pending accepted refused) de l'offre pour l'influenceur

**Comment by Mystogunn** [comment]
@chheue la requête renvoie déjà le status du apply user

**Comment by chheue** [comment]
@Mystogunn Ca renvoie un tableau d'objet avec "apply" mais il faudrait un "status" juste pour l'influenceur connecté
